# Stage 1: build
FROM node:20-alpine AS builder-frontend
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# Stage 2: production
FROM nginx:alpine
COPY --from=builder-frontend /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
